In [1]:
import numpy as np

In [17]:
# printing of 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# printing of 2D array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# to get the dimension of an numpy array, use .ndim
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#to get the shape 
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
#get the type, use .dtype, here d represents data
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [12]:
#if you wanna change the int type or save your 'a' value with your preferred size,because we knew that size of a is lessthan
#32 bytes
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [13]:
#earlier the type was int32, now it is int16
a.dtype

dtype('int16')

In [15]:
#there are couple diff imp functions
#the o/p is 2, because its int16, if it is int32, the o/p would be 4 bites
a.itemsize

2

In [19]:
#total size would be multiplication of a.size * a.itemsize
a.size * a.itemsize

12

In [20]:
# or another way to do that is just no.of bytes
a.nbytes

12

In [21]:
#Accessing/Changing specific elements,rows,columns etc

In [76]:
#imagine we have a 2D array, its kind of long, like a 2*7 array
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
#to know the dimension of the array
a.shape

(2, 7)

In [26]:
#now, what if we want to get a specific element? we can use a notation [r, c] r is row, c is colomn
#if we want to get 13 element
#here 1 is the second row as in 0 is the first row and 1 is the second row, and 5 is the 5th element from 0 (just like indices)
a[1,5]

13

In [27]:
#you can also use the negative indices, similar to lists
a[1,-2]

13

In [33]:
#how to get a specific row
#here 0 is the first row and space and : defines the whole row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#how to get a specific column
#: defines all the rows and 2 defines column, as in 0 is the first,1 is the second and 3 is the third
a[:, 2]

array([ 3, 10])

In [34]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
#getting a little fancy, [startindex:endindex:stepsize]
#assume we need every other element b/w 2 and 6 in the first row
a[0,1:6:2]

array([2, 4, 6])

In [36]:
#if i want to change 13 number in 'a' to 20
a[1,5] = 20

In [37]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
#if you wanna change an entire column
a[:,2]= 5

In [40]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
#or if you wanna them to be two diff numbers of same shape, just mention those numbers
a[:,2] = [10,11]
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 11 11 12 20 14]]


In [43]:
#3D Example

In [44]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
#if you wanna get specific element, the recommended mentod is (work outside in)
#let say we want to have 4 from the above o/p,so i want 4 from the 1234 matrix
#b[0] is the first matrix at 0 index
#now the second row, so its 1 index
#now we want 4, so its at 1 index
b[0,1,1]

4

In [48]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [50]:
b[:,1,0]

array([3, 7])

In [51]:
#lets say
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
#lets say you wanna replace the whole above output, then
b[:,1,:] = [[9,9],[8,8]]
#as long as its the same dimension, its gonna work

In [53]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [54]:
#Initialising different types of arrays

In [58]:
#start off with initialising with all 0's matrix and to do tht theres a nice built-in function called np.zeros
#if you want a 2*2 or 2*3 or 3*2 or any other zero martix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [61]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
#you can do it 3D also
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [63]:
#you can even do 4D also

In [64]:
np.zeros((2,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [65]:
#All 1's matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
#you can go ahead and specify the data type size too. imahine you want all ones with dtype int32
np.ones((4,2,2,2), dtype = 'int32')
#observer the above o/p and below o/p

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [74]:
#any other matrix other than 1's and 0's
np.full((2,2),99)
#here (2,2) is the shape and 99 is just a number you entered

array([[99, 99],
       [99, 99]])

In [75]:
np.full((2,3),(41,51,61))

array([[41, 51, 61],
       [41, 51, 61]])

In [77]:
#thers another method called full_like.
#it basically allows us a shape thats already built.
#at line 21 we have an array 'a', imagine that you want to have your number in the same shape
np.full_like(a,6)
#now check this o/p and that 'a' o/p. They both have same shape

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [79]:
#if i dont use full_like, you can also use a.shape inside
np.full(a.shape,6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [80]:
#lets say we want to initialise a matrix of random decimal numbers
np.random.rand(4,2)

array([[0.37002504, 0.858749  ],
       [0.71939286, 0.19843499],
       [0.45854372, 0.40260069],
       [0.04070401, 0.84634344]])

In [82]:
#if you wanna pass in something like 'shape', you can do is .random.random_sample(xxxx)
np.random.random_sample(a.shape)
#now that gives the o/p as same shape as our 'a'

array([[0.44283516, 0.75938575, 0.21947067, 0.44974399, 0.31415307,
        0.81231513, 0.48687879],
       [0.635266  , 0.46186103, 0.58562741, 0.86406559, 0.14814392,
        0.03895679, 0.38516197]])

In [90]:
#what if you didnt want just random decimal numbers, you want the random integer values?
#here 4 is the start index, 9 is the end index, size is the shape
#if you dont mention the start index, it will automatically take 0 as its start index
np.random.randint(4,9, size=(3,3))

array([[7, 7, 4],
       [4, 6, 5],
       [5, 8, 4]])

In [95]:
np.random.randint(-4,12, size=(4,3))

array([[ 4,  9, -1],
       [-1,  9,  1],
       [ 6,  6,  6],
       [-1, 11,  5]])

In [97]:
#if you want to get the identity matrix
np.identity(3)
#this one only needs one parameter,because identity matrix by nature is a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [99]:
#lets say we want to repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)
#herre arr is an array we created, r1 is the variable we reated
#np.repeat(your array,no.of times you want it to be repeated)

[1 1 1 2 2 2 3 3 3]


In [107]:
#if you want to mention the axis,like if you want to see your repeated array column wise
#mention your array in 2D--> np.array([[1,2,3]])
#and then in repeat code line, mention the axis=0
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis=0)
print(r1)
#so basically, axis would be either 0 or 1. The above example is 1 and this example is 0

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [110]:
np.random.randint(0,10, size=(5,5))

array([[4, 4, 5, 5, 1],
       [8, 5, 8, 5, 7],
       [5, 9, 5, 6, 2],
       [8, 4, 3, 7, 1],
       [3, 0, 4, 3, 3]])

In [111]:
#write a code to print below matrix
#[[1. 1. 1. 1. 1.]
# [1. 0. 0. 0. 1.]
# [1. 0. 9. 0. 1.]
# [1. 0. 0. 0. 1.]
# [1. 1. 1. 1. 1.]

In [117]:
#first create ones matrix
ones= np.ones((5,5))
print(ones)
#next create zeros matrix,but a 3*3 matrix, since in our question we only have a 3*3 matrix.
#replace the 0 at (1,1) location with 9, asked in as question
zeros = np.zeros((3,3))
zeros[1,1] = 9
print(zeros)
#finally we need to replace the middle part of ones matrix
#1:4 is first row to the third row and 1:4 is first column to the third column
ones[1:4,1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [118]:
#lets imagine i have an array 'a'
a = np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [119]:
#so now i would like to edit 'b' and change the value at 0 index position
b[0] = 100
b

array([100,   2,   3])

In [120]:
#lets see whether it effected 'a' as well or not.
a

array([100,   2,   3])

In [121]:
#it had affected 'a' as well

In [122]:
#so if you want to prevent it, you need to mention .copy()
a=np.array([100,200,300])
b=a.copy()
print(a)
print(b)

[100 200 300]
[100 200 300]


In [123]:
b[0]=400
print(a)
print(b)
#voila! check the o/p below

[100 200 300]
[400 200 300]


Mathematics

In [131]:
#we can do element wise arithmetic ops like add,sub,multi etc etc
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [125]:
a+2

array([3, 4, 5, 6])

In [126]:
a-2

array([-1,  0,  1,  2])

In [127]:
a*2

array([2, 4, 6, 8])

In [128]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [129]:
a+=2

In [130]:
a

array([3, 4, 5, 6])

In [132]:
a

array([1, 2, 3, 4])

In [133]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [134]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [135]:
# we can take the Sin of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [136]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#####Linear Algebra######

In [137]:
#Lets say we have two matrices and the big diff with Linear Algebra is like, we are not doing the element wise computation-
#observe the above examples. We just added +2 to every element, we subtracted -2 to every element, we did element wise comp-
#-utation, in linear algebra you tryna multiply matrices or add matrices or subtract matrices

In [142]:
a= np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
#if you remember linear algebra, the columns of first matrix should be equal to the rows of the second matrix
#thats why 3 in 'a' in columns and 3 in 'b' in rows

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [143]:
a*b
#if you do a*b, its not gonna work because they have multiple sizes.

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [144]:
#it has a matrix multiply function
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [145]:
#lets say i want to find the determinant of a matrix
#if you remember algebra, identity matrix will have a determinant of 1
c=np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [146]:
#linearalgebra.determinant to get the determinant
np.linalg.det(c)

1.0

In [147]:
#Reference link (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
#Determinant
#Trace
#Singular Vector Decomposition
#Eigen Values
#Matrix Norm
#Inverse
#etc etc

######Statistics####

In [148]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
#lets just say, you want min of it
np.min(stats)

1

In [150]:
#similarly max()
np.max(stats)

6

In [151]:
#you can also do it like row basis
#it gives minimum of 1st array and minimum of second array inside your stats matrix
np.min(stats, axis=1)

array([1, 4])

In [152]:
np.max(stats, axis=1)

array([3, 6])

In [153]:
#to know sum of all the elements in the matrix
np.sum(stats)

21

In [154]:
#if you mention axis as 1, it will add the rows, if you mention axis as 0, it will add columns
np.sum(stats, axis=1)

array([ 6, 15])

In [155]:
np.sum(stats,axis=0)

array([5, 7, 9])

Reorganising arrays

In [156]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [158]:
#you can also check the shape
before.shape
#its a 2*4 matrix

(2, 4)

In [159]:
#lets say we want to make it 8*1 matrix
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [161]:
#may be i want it to be a 4*2
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [162]:
#Vertically stacking vectors
#dimensions are imp in vertical stacks as well
#lets say we have these two arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
#i want to stack 1234 on top of 5678, i can do is
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [163]:
#what you can do is keep passing them
np.vstack([v1,v2,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [167]:
#Horizontally stacking vectors
#we have these two matrices
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
#what i want is h2 to be on the back of h1
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##Miscellaneous##

Load Data from File

In [4]:
#imagine you have some sort of text file or other source of data. And for whatever reason you choose not to use pandas,but
#you wanna load all that data from that file into a numpy array,we can do that
#np.genfromtxt('filename', delimiter=',')
#delimiter is just to seperate the data

Advanced Indexing and Boolean Masking

In [5]:
#if i want,where in our saved file which we worked above is greater than 50.
#suppose file name is data.txt and you assigned it to a variable called Filedata
#Filedata > 50 
#it gives TRUE at all the instances where numbers are greater than 50 and FALSE where all the numbers are lessthan 50

In [6]:
#you can do lessthan, you can do >= or <= etc

In [7]:
#if you want to get all the values greater than 50
#you can do is Filedata[Filedata>50], remember Filedata is the variable name we have given to the file data.txt

In [10]:
#,you can index with a list in Numpy
import numpy as np

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

In [12]:
#if you want to know any of the values is greater than 50 in our data.txt file
#np.any(Filedata > 50, axis =0)
#we can also do np.all
#((Filedata > 50) & (Filedata < 100))
#gives the boolean values
#~((Filedata > 50) & (Filedata < 100))
#it gives the reverse of the boolean values, ~ is like not operator basically